server:
  port: 8081

application:
  kafka:
    topic: "from-client-to-comment"
    topic2: "from-comment-to-client"

spring:
  kafka:
   consumer:
     group-id: "test-group"
     bootstrap-servers: "localhost:9092"
     client-id: "demo-consumer"
     auto-offset-reset: earliest
   producer:
      bootstrap-servers: "127.0.0.1:9092"
      client-id: "demo-producer"

  application:
    name: beer-library-client

  datasource:
    # Эти свойства будут перегружены свойствами в docker-compose.yml
    url: jdbc:postgresql://localhost:5431/db2
    username: usr
    password: pwd

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false

    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true