server:
  port: 8084

application:
  kafka:
    topic: "from-client-to-comment"
    topic2: "from-comment-to-client"

spring:
  application:
    name: library-comment-service
  kafka:
    consumer:
      group-id: "test-group"
      bootstrap-servers: "localhost:9092"
      client-id: "demo-consumer"
      auto-offset-reset: earliest

  datasource:
    # Эти свойства будут перегружены свойствами в docker-compose.yml
    url: jdbc:postgresql://localhost:5430/db
    username: usr
    password: pwd

  sql:
    init:
      mode: always

  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false

    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true